---
version: "3.9"
services:
  demo_svc:
    image: demo-svc:dont_push
    container_name: demo_svc
    hostname: demo_svc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local_backend
    environment:
      - VIRTUAL_HOST=demo-svc.local
      - VIRTUAL_PORT=8080
    ports:
      - "8080:8080"
    expose:
      - "8080"
networks:
  local_backend:
    external: true
    name: local_backend
