server:
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo-svc
    username: demo-svc
    password: demo-svc
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
