server:
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://mysql-8-0-31:3306/demo-svc
    username: demo-svc
    password: demo-svc
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:  # TRACE/DEBUG/INFO/WARN/ERROR/FATAL/OFF
    root: INFO
    org.springframework.web: INFO
    com.example.demo: DEBUG
#  pattern:
#    console: "{\"t\":\"%date{ISO8601}\",\"l\":\"%level\",\"f\":\"%file\",\"ln\":\"%line\",\"m\":\"%msg\",\"thread\":\"%thread\"}%n"
